FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    gdb \
    libgtest-dev \
    git \
    vim \
    && rm -rf /var/lib/apt/lists/*

RUN cd /usr/src/gtest && cmake . && make && cp lib/*.a /usr/lib

WORKDIR /workspaces/bubblegame

SHELL ["/bin/bash", "-c"]
