# Dockerfile for temporary development environment
# This Dockerfile can change a lot depending on what needs to be experimented with.
# Thus, it is going to be changed a LOT depending on what I want to do.

FROM ubuntu:24.04

# Install build tools
RUN apt-get update && \
    apt-get install -y build-essential g++ make && \
    apt-get clean

# Set working directory inside container
WORKDIR /app

# Copy project files into the container
COPY . .

# Build the project
RUN make build

# Compile boardgen using the built object file
RUN g++ -std=c++23 -Wall -Iinclude boardgen.cpp build/gameboard.o -o boardgen

# When the container runs, output boardgen's result
CMD ["./boardgen"]
